/**
 * Copyright 2012, Raxa
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * This class provides util methods and constants that are shared by the core, apps and modules
 */

// TODO: https://raxaemr.atlassian.net/browse/RAXAJSS-382
// Move everything inside of Util so not in global scope. Then update
// references from other parts of application. E.g. page enums is a low hanging
// fruit to start with 

/* Phone Number Validation */
// Fails in Sencha Touch when using basic touch library instead of ext-all
// Ext.apply(Ext.form.VTypes, {
//     phone: function (value, field) {
//         return value.replace(/[ \-\(\)]/g, '').length == 10;
//     },
//     phoneText: 'Invalid, number must be 10 digits',
//     phoneMask: /[ \d\-\(\)]/
// });

window.onhashchange = function(e) {
    var location = window.location.hash.substring(1);
    console.log(location);
    //moving back from history
    if(location === "") {
        if(Ext.getCmp('structureView') !== undefined) {
            Ext.getCmp('structureView').hide();
        }
        Ext.getCmp('treatment-panel').animateActiveItem(UNSTRUCTURED_HISTORY_VIEW , {
            type: 'slide',
            direction: 'left'
        });
        if(friendRecord.data){
            if(Ext.getCmp('addReferButton') !== undefined) {
                Ext.getCmp('addReferButton').show();
            }
        }
    } else if (location === "history") {
        Ext.getCmp('history-panel').setActiveItem(UNSTRUCTURED_HISTORY_VIEW);

        Ext.getCmp('treatment-panel').animateActiveItem(HISTORY_OVERVIEW, {
            type: 'slide',
            direction: 'right'
        });
    }
};

var HOST;
var DEFAULT_HOST = 'https://api.raxa.io';
if (localStorage.getItem("host") === null) {
    HOST = DEFAULT_HOST; 
} else { 
    HOST = localStorage.getItem("host"); 
}
var CONCEPT_HOST = 'http://search.raxa.io:4000';
var CHUNK_UPLOAD_HOST = 'http://raxa.org:3001';

var username;
var password;
var timeoutLimit = 150000;
var hospitalName = 'JSS Hospital';
var resourceUuid = {
    "raxaEMRconfig": {
        "resource": "concept",
        "queryTerm": "raxaEMRconfig",
        "varName": "raxaEMRconfig",
        "displayName": "RAXA EMR CONFIG"
    }
};

// This is the name of the friend Identifier Type that is being Auto-Generated by the IDGen Module.
// Put the Identifier Type Name in between the /.* and the .*/
var idPattern = /.*RaxaEMR Identification Number.*/;

var DEFAULT_PRESCRIPTION_QUANTITY = 15;

//Open Mrs age limits
 


//BMI WHO Constants
var WHO_BMI_VSUNDERWEIGHT = 15;
var WHO_BMI_SUNDERWEIGHT = 16;
var WHO_BMI_UNDERWEIGHT = 18.5;
var WHO_BMI_NORMAL = 25;
var WHO_BMI_OVERWEIGHT = 30;
var WHO_BMI_OBESE = 35;
var WHO_BMI_SOBESE = 40;

// BMI Custom Constants
var BMI_MAX = 60;
var BMI_HEIGHT_MAX = 300;
var BMI_HEIGHT_MIN = 0;
var BMI_WEIGHT_MAX = 800;
var BMI_WEIGHT_MIN = 0;

// Enum for Key Maps
var KEY = {
    DELETE: 8,
    ENTER: 13,
    ESCAPE: 27
};
var keyMap = {
};

// Enum for Registration Module Page Numbers
var REG_PAGES = {
    HOME: {
        value: 0,
        name: "home"
    },
    REG_1: {
        value: 1,
        name: "registrationpart1"
    },
    REG_CONFIRM: {
        value: 2,
        name: "registrationconfirm"
    },
    ILLNESS_DETAILS: {
        value: 3,
        name: "illnessdetails"
    },
    REG_BMI: {
        value: 4,
        name: "registrationbmi"
    },
    SEARCH_1: {
        value: 5,
        name: "searchpart1"
    },
    SEARCH_2: {
        value: 6,
        name: "searchpart2"
    },
    SEARCH_CONFIRM: {
        value: 7,
        name: "searchconfirm"
    }
};

var UITIME = 120000;
var ONEDAYMS = 86400000;
var MONTHSINAYEAR = 12;
var diffinUTC_GMT = 5.5;    // TODO: Fix this hack, which only works in timzeones <= IST :) instead should get time from OpenMRS server, ideally

//number of hours for everything to be before now
//OpenMRS checks whether encounters are ahead of current time --
//if a system clock is ahead of OpenMRS clock, some things can't be posted
//therefore, we need to fudge our time a few mins behind
var TIME_BEFORE_NOW = 0.1;

// The Util class provids several methods that are shared by the core, apps and modules
var Util = {
    conceptVersion : 20121206,
    // Enum to capture pages in each app. E.g. Util.PAGES.SCREENER.PAGE_NAME
    PAGES: {},
    
    //string to know whether a friend is able to be screened to
    DOCTOR_ATTRIBUTE: 'isOutfriendDoctor - true',

    //all the provider attributes used in friend record print
    REQUIRED_PROVIDER_ATTRIBUTES: [ "Specialty", "Degree", "Registration Number", "Degree", "Timings Line 1", "Primary Contact" , "Email"],

    ALL_PROVIDER_ATTRIBUTES: [ "Specialty", "Degree", "Registration Number", "Degree", "Timings Line 1", "TimingsLine2", "Primary Contact" , "Email", "Secondary Contact", "isOutfriendDoctor"],
    ALL_PERSON_ATTRIBUTES: ["Email", "Health Center", "Primary Contact", "Secondary Contact"],

    DEFAULT_LOCATION: "GAN",
    OPEN_MRS_MIN_AGE : 0,
    OPEN_MRS_MAX_AGE : 120,
    Taken_Morning : "morning ** true.",
    Taken_Day : "day ** true.",
    Taken_Even : "evening ** true.",
    Taken_Night : "night ** true.",
    
    //not allowing modals to pop up after certain time
    MODAL_POPUP_WAIT_TIME : 700,
    SEARCH_WAIT_TIME : 700,

    //how many letters required before searching (drug, friend, investigation, etc)
    LETTERS_REQUIRED_TO_SEARCH : 3,

    /*
     * Listener to workaround maxLength bug in HTML5 numberfield with Sencha
     * Number field fails to enforce maxLength, so must add JavaScript listener
     * http://stackoverflow.com/questions/9613743/maxlength-attribute-of-numberfield-in-sencha-touch
     */
    maxLengthListener: function(maxLength) {
        return {
            keyup: function(textfield, e, eOpts) {
                var value = textfield.getValue() + '';
                var length = value.length;

                var MAX_LENGTH = maxLength;
                if (length > MAX_LENGTH) {
                    textfield.setValue(value.substring(0, MAX_LENGTH));
                    return false;
                }
            }
        };
    },

    /**
     *Returns the value of time difference in UTC and GMT
     *@return diffinUTC_GMT
     */
    getUTCGMTdiff: function() {
        return diffinUTC_GMT;
    },
    
    /**
     *Returns the value of time for updating the friends waiting title and automatic refresh
     *@return UITIME 
     */
    getUiTime: function () {
        return UITIME;
    },
    
    /**
     *Returns how many days are left from now to date passed in
     */
    daysFromNow: function(futureDate) {
        var future = new Date(futureDate);
        var now = new Date();
        return Math.ceil((future.getTime()-now.getTime())/ONEDAYMS);
    },

    monthsFromNow: function(futureDate) {
        var future = new Date(futureDate);
        var now = new Date();
        return Math.ceil((future.getFullYear()-now.getFullYear())*MONTHSINAYEAR + future.getMonth()-now.getMonth());
    },

    daysBetween: function(pastDate, futureDate) {
        var future = new Date(futureDate);
        var past = new Date(pastDate);
        return Math.abs(Math.ceil((future.getTime()-past.getTime())/ONEDAYMS));
    },

    monthsBetween: function(pastDate, futureDate) {
        var future = new Date(futureDate);
        var past = new Date(pastDate);
        return Math.abs((future.getFullYear()-past.getFullYear())*MONTHSINAYEAR + future.getMonth()-past.getMonth())
    },

    /**
     *Gets the current time
     */
    getCurrentTime: function(){
        return this.Datetime(new Date(), this.getUTCGMTdiff());
    },

    /**
     *Returns the value of TimeoutLimit for login timeout 
     *@return timeoutLimit for timeout in login 
     */
    Datetime: function (d, hours) {
        if (typeof hours == 'undefined') {
            hours = 0;
        }
        //subtracting time in case our clock is ahead of OpenMRS clock
        hours = hours+TIME_BEFORE_NOW;
        var MS_PER_MINUTE = 60000;
        var k = new Date(d - (60 * hours) * MS_PER_MINUTE);

        function pad(n) {
            return n < 10 ? '0' + n : n;
        }
        return k.getFullYear() + '-' + pad(k.getMonth() + 1) + '-' + pad(k.getDate()) + 'T' + pad(k.getHours()) + ':' + pad(k.getMinutes()) + ':' + pad(k.getSeconds()) + 'Z';
    },
    getTimeoutLimit: function () {
        return timeoutLimit;
    },

    getHospitalName: function () {
        return hospitalName;
    },

    /**
     * Returns all the headers required for Basic Authenticated REST calls
     * @return headers object that includes Authorization, Accept and Content-Type
     */
    getBasicAuthHeaders: function () {
        var headers = {
            "Authorization": localStorage.getItem("basicAuthHeader"),
            "Accept": "application/json",
            "Content-Type": "application/json"
        };
        return headers;
    },

    /**
     * Logout the current user. Ends the current session
     * keepLocation tells whether to reload the page
     */
    logoutUser: function (keepLocation) {      
        Ext.Ajax.request({
            url: HOST + '/ws/rest/v1/session',
            withCredentials: true,
            useDefaultXhrHeader: false,
            method: 'DELETE'
        });
        localStorage.removeItem('basicAuthHeader');
        localStorage.removeItem('privileges');
        localStorage.removeItem('Username');
        localStorage.removeItem('loggedInUser');
        localStorage.removeItem('loggedInProvider');
        localStorage.removeItem('session');
        for(var i=0; i<Util.ALL_PROVIDER_ATTRIBUTES.length; i++){
            var attributeName = "provider" + Util.ALL_PROVIDER_ATTRIBUTES[i].replace(/\s+/g, '');
            localStorage.removeItem(attributeName);
        }
        for(var i=0; i<Util.ALL_PERSON_ATTRIBUTES.length; i++){
            var attributeName = "person" + Util.ALL_PERSON_ATTRIBUTES[i].replace(/\s+/g, '');
            localStorage.removeItem(attributeName);
        }
        if(!keepLocation){
            if(Util.isAndroid()){
                location.reload(true);
            }else{
                location.reload();
            }
        }
    },

    generateUUID: function () {
        var d = new Date().getTime();
        var uuid = 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'.replace(/[x]/g, function(c) {
            var r = (d + Math.random()*16)%16 | 0;
            d = Math.floor(d/16);
            return (c=='x' ? r : (r&0x7|0x8)).toString(16);
        });
        return uuid;
    },  
    
    uuidLoadedSuccessfully: function(){
        if( this.checkAllUuidsLoaded()) {
            return true;
        } else {
            window.location = "../";
        }
    },

    checkAllUuidsLoaded: function() {
        var that=this;
        var expectedUuidCount=0;
        var uuidsLoadedCount=0;
        var uuidsNotFound = "";
        for (var key in resourceUuid) { 
            expectedUuidCount++;
            var item = resourceUuid[key].varName + "Uuid" + resourceUuid[key].resource;
            if(localStorage.getItem(item) !== null){
                uuidsLoadedCount++;
            } else {
                uuidsNotFound += (item + ", ");
                this.getAttributeFromREST(resourceUuid[key].resource, resourceUuid[key].queryTerm, resourceUuid[key].varName, resourceUuid[key].displayName);
            }
        }
        
        if (expectedUuidCount == uuidsLoadedCount) {
            console.log("UUIDs expected = " + expectedUuidCount + ". UUIDs loaded " + uuidsLoadedCount);
            return true;
        } else {
            console.log("UUIDs expected = " + expectedUuidCount + ". UUIDs loaded " + uuidsLoadedCount);
            console.log("Uuid's which failed to load were:", uuidsNotFound);
            return false;
        }
    },
    

    /**
     * Saves the Basic Authentication header to Localstorage
     * Verifies if username + password is valid on server and saves as Base4 encoded string of user:pass
     */
    saveBasicAuthHeader: function (username, password) {
        Util.logoutUser(true); //Delete existing logged in sessions
        //Check login and save to localStorage if valid
        //We are using a synchronous XMLHttp Request instead of an Asynchronous AJAX request
        var xmlReq = new XMLHttpRequest();
        xmlReq.addEventListener("error", transferFailed, false);
        xmlReq.open("GET", HOST + '/ws/rest/v1/session', false);
        xmlReq.setRequestHeader("Accept", "application/json");
        xmlReq.setRequestHeader("Authorization", "Basic " + window.btoa(username + ":" + password));
        xmlReq.send();
        function transferFailed(){
            Ext.Msg.alert('Network Error',Ext.i18n.appBundle.getMsg('RaxaEmr.controller.session.network'));
        }
        if (xmlReq.status == "200") {
            var authenticated = Ext.decode(xmlReq.responseText).authenticated;
            if (authenticated) {
                localStorage.setItem("basicAuthHeader", "Basic " + window.btoa(username + ":" + password));
            } else {
                localStorage.removeItem("basicAuthHeader");
            }
        }
    },

    /**
     * Returns all the modules in Raxa
     * @return [ 'login', 'screener', ....]
     */
    getModules: function () {
        //always keep login at first position as its app path is different
        return ['login', 'screener', 'registrationextjs4', 'pharmacy', 'chw', 'outfriend', 'laboratory', 'friendfacing', 'admin', 'billing'];
        
    },

    /**
       *Return selected module in Raxa and by changing the module text font .
       *@return [ 'LOGIN', 'SCREENER', ....]
       */
    getSelectModules: function () {
        var module=[];
        for (var i = 0; i < Util.getModules().length ; i++) {
            var text = Util.getModules()[i];
            var changedText = "";
            switch(text) {
                case 'login' :
                    changedText = 'Dashboard';
                    break;
                case 'screener' :
                    changedText = 'Screener';
                    break;
                case 'registration' :
                    changedText = 'Registration';
                    break;
                case 'registrationextjs4':
                    changedText = 'Registration Desktop';
                    break;
                case 'pharmacy' :
                    changedText = 'Pharmacy';
                    break;
                case 'chw' :
                    changedText = 'Chw';
                    break;
                case 'outfriend' :
                    changedText = 'Opd';
                    break;
                case 'laboratory' :
                    changedText = 'Laboratory';
                    break;
                case  'friendfacing':
                    changedText = 'friend Facing';
                    break;
                case  'admin':
                    changedText = 'Admin';
                    break;
                default :
                    changedText = 'You dont have permission to access any Module';
                    break;
            }
            var dropDownObj = {
                text : changedText , 
                value:Util.getModules()[i]
            };
            module.push(dropDownObj);
        } 
        return module;
    },
    

    getApps: function () {
        //always keep login at first position as its app path is different
        return ['gotStatins', 'problemList'];
    },
    /**
     *Generate six digit randomly generated Device Id  
     *Checks if any key with name "deviceId" is previously stored in localStorage, returns it if availaible
     *@return deviceId
     *
     */
    getDeviceId: function () {
        var deviceId;
        //Checks if localStorage already has deviceId stored in it        
        if (localStorage.getItem("deviceId") === null) {
            var randomNumber = [];
            for (var i = 0; i < 6; i++) {
                //generates random digit from 0 to 10
                randomNumber[i] = (Math.floor(Math.random() * 10));
            }
            deviceId = randomNumber.join('');
            localStorage.setItem("deviceId", deviceId);
            console.log('6-digit randomly generated Device Id: ' + deviceId + ' & is stored in localStorage');

        } else {
            // gets the value of deviceId if available in localStorage 
            deviceId = localStorage.getItem("deviceId");
            console.log('6-digit randomly generated Device Id that was stored in localStorage:' + deviceId);
        }
        return deviceId;
    },

    /**
     * gets the friend Identifier generated by the IDGen Module
     * Note: The Identifier type must be the 3rd in the list (ie at position 2) for this to work properly.
     */
    getfriendIdentifier: function () {
        var locationString = arguments[0];
        if(arguments[0] === undefined){
            locationString = this.DEFAULT_LOCATION;
        }
        var generatedId = locationString +(Math.floor(Math.random()*1000000)).toString();
        url = HOST + '/ws/rest/v1/friend?q='+generatedId,
        xmlHttp = new XMLHttpRequest(); 
        xmlHttp.open( "GET", url , false );
        xmlHttp.setRequestHeader("Accept", "application/json");
        xmlHttp.setRequestHeader("Authorization", localStorage.getItem("basicAuthHeader"));
        xmlHttp.send();
        var jsonData = JSON.parse(xmlHttp.responseText);
        if (xmlHttp.status == "200") {
            if(jsonData.results.length > 0) {
                return(Util.getfriendIdentifier());
            } else {
                return generatedId;
            }
        }
    },
    
    //  getX: function(){return 5},

    //Function to help share Models between ExtJS and Sencha Touch 2
    platformizeModelConfig: function (extJsModelConfig) {
        if (Ext.versions.extjs) {
            return extJsModelConfig; // nothing to change, we are on ext
        } else if (Ext.versions.touch) {
            // transform to Sencha Touch 2 data model
            var config = {
                extend: extJsModelConfig.extend,
                config: extJsModelConfig
            };
            delete config.config.extend;
            return config;
        } else {
            Ext.Error.raise('Could not recognize Library');
        }
    },
    
    // Returns session, a JSON. so far this includes:
    // - person uuid
    // - person preferredName display
    getSession: function() {
        if(localStorage.session){
            return JSON.parse(localStorage.session);
        }
        return null;
    },

    getAttributeFromREST: function (resource, queryParameter, varName, display) {
        //Ajax Request to get Height / Weight / Bmi Attribiutes from Concept Resource
        Ext.Ajax.request({
            url: HOST + '/ws/rest/v1/' + resource + '?q=' + queryParameter + '&v=full',
            method: 'GET',
            disableCaching: false,
            headers: Util.getBasicAuthHeaders(),
            failure: function (response) {
                console.log('GET failed with response status: ' + response.status); // + response.status);
            },
            success: function (response) {
                // console.log("getAttributeFromRest ... resource: " + resource + ", queryParameter: " + queryParameter + ", varName:" + varName + " RESPONSE: " + response.responseText);
                for (var i = 0; i < JSON.parse(response.responseText).results.length; ++i) {
                    if (JSON.parse(response.responseText).results[i].display == display) {
                        if(display === 'RAXA EMR CONFIG')   {
                            var responseJSON = JSON.parse(response.responseText).results[i];
                            var configConceptDescription = JSON.parse(responseJSON.descriptions[0]['display']);
                            var uuidsInConfigArray = configConceptDescription.uuids;
                            var versionOfConfig = configConceptDescription.version;
                            //Comment Date: Jun 18 2013 by Piyush Madan (piyush.madan@raxa.org)
                            //TODO:
                            //Following check on concept version has been removed as we are not updating configUuid version in backend. Because this 
                            //version will go for webapp only and we need new uuid to load. Following code will be uncommented
                            //when we update webapp version & App Store in next release cycle and correnspondingly update backend version.
                            // if (versionOfConfig === Util.conceptVersion)
                            // {
                                for(var i in uuidsInConfigArray)
                                 {
                                    localStorage.setItem(uuidsInConfigArray[i]['name'],uuidsInConfigArray[i]['uuid']);
                                 }
                                // console.log(i+ ' concepts have been unpacked from config concept from server');
                           //  }
                           //  else {
                           //      Ext.Msg.alert('Update version','Your Raxa Version seems to be out of date. For assistance email please contact Raxa help');
                           //  }
                            }
                        if (resource != 'location') {
                                localStorage.setItem(varName + "Uuid" + resource, JSON.parse(response.responseText).results[i])
                            } else {
                                localStorage.setItem(varName + "Uuid" + resource, display)
                            }
                    }
                }
            }
        });
    },

    getPersonUuidFromProviderUuid: function (uuid) {
        Ext.Ajax.request({
            url: HOST + '/ws/rest/v1/provider/' + uuid,
            method: 'GET',
            disableCaching: false,
            headers: Util.getBasicAuthHeaders(),
            failure: function (response) {
                console.log('GET failed with response status: ' + response.status);
            },
            success: function (response) {
                if (console.log(JSON.parse(response.responseText).person.uuid) != null) {
                    return JSON.parse(response.responseText).person.uuid;
                } else {
                    // TODO: should throw an exception, not return the wrong string
                    // Ext.Error.raise('<Error Text>');
                    return "provider with given uuid does not exist";
                }
            }
        });
    },

    KeyMapButton: function(ComponentName,keyName)
    {
        if(keyMap.keyName!=null)
        {
            this.DestroyKeyMapButton(keyName);
        }
        keyMap.keyName = Ext.create('Ext.util.KeyMap',Ext.getBody(), [
        {
            key: keyName,
            shift: false,
            ctrl: false,
            fn:function(){
                var element = Ext.getCmp(ComponentName);
                element.fireEvent('click',element);

            }
        }
        ]);

    },

    DestroyKeyMapButton: function(keyName)
    {
        keyMap.keyName.destroy(true);
        keyMap.keyName=null;
    },

    getProviderUuidFromPersonUuid: function (uuid) {
        Ext.Ajax.request({
            url: HOST + '/ws/rest/v1/provider?v=full',
            method: 'GET',
            disableCaching: false,
            headers: Util.getBasicAuthHeaders(),
            failure: function (response) {
                console.log('GET failed with response status: ' + response.status);
            },
            success: function (response) {
                var allProviders = JSON.parse(response.responseText).results;
                for(i=0; i<allProviders.length; i++){
                    if(allProviders[i].person.uuid === uuid){
                        console.log("success");
                        localStorage.setItem("loggedInProvider", allProviders[i].uuid);
                        return allProviders[i].uuid;
                    }
                }
                return "provider with given uuid not found";
            }
        });
    },
    
    /**
     * Returns the uuid of the logged in provider
     */
    getLoggedInProviderUuid: function(){
        if(localStorage.getItem("loggedInProvider")){
            return localStorage.getItem("loggedInProvider");
        }
        else{
            // TODO: This is betterr, agreed, but it's breaking existing code when I try to run the native app :)
            //  Solving one thing at a time...
            Ext.Error.raise('Provider is not logged in');
            return null;
        }
    },
    
    /**
     * Runs before each module. Checks whether user has the privilege to view a specific module
     * If not, redirects to login page.
     * If so, returns true.
     */
    checkModulePrivilege: function(module){
        var privileges = localStorage.getItem("privileges");
        if(privileges!== null && (privileges.indexOf('RaxaEmrView '+module)!==-1 || privileges.indexOf('all privileges')!==-1)){
            return true;
        }
        else{
            window.location = "../";
        }
    },

    /**
     * Sends an alert according to given parameters
     */
    sendAlert: function(alertParams){
        var alertParam = Ext.encode(alertParams);
        Ext.Ajax.request({
            url: HOST + '/ws/rest/v1/raxacore/raxaalert',
            method: 'POST',
            disableCaching: false,
            headers: Util.getBasicAuthHeaders(),
            params: alertParam,
            failure: function (response) {
                console.log('POST alert failed with response status: ' + response.status);
            }
        });
    },
    
    /**
     * The message to send when a resource fails to load from the server
     */
    getMessageLoadError: function() {
        return "Unable to read from server";
    },
    
    /**
     * Message to send when a resource fails to write to a server
     */
    getMessageSyncError: function() {
        return "Unable to write to server";
    },
    
    /**
     * Creates a new drug in OpenMRS based on given parameters
     * newDrugParam contains:
     * drugName
     * manufacturer
     * supplier
     * cost
     * price
     * dosageForm
     * minimumDailyDose
     * maximumDailyDose
     * units
     */
    submitNewDrug: function(newDrugParam, callback) {
        console.log(newDrugParam);
        //getting drug concept from OpenMRS
        //First, we check if the new drug concept exists in RxNorm/Openmrs -- if not, we will have to create
        //a new concept
        Ext.Ajax.request({
            url: HOST + '/ws/rest/v1/concept?q='+newDrugParam.genericName+"&v=full",
            method: 'GET',
            disableCaching: false,
            headers: Util.getBasicAuthHeaders(),
            success: function (response) {
                var jsonResponse = Ext.decode(response.responseText);
                var j=0;
                var foundDrugConcept = false;
                while(j<jsonResponse.results.length && !foundDrugConcept){
                    if (jsonResponse.results[j].conceptClass.description === "Drug"){
                        foundDrugConcept = true;
                        newDrugParam.conceptUuid = jsonResponse.results[j].uuid;
                        this._postNewDrug(newDrugParam, callback);
                    }
                    j++;
                }
                if(!foundDrugConcept){
                    //we need to make the concept as we didn't find it
                    this.postConceptForNewDrug(newDrugParam, callback);
                }
            },
            failure: function() {
                Ext.Msg.alert("Error", Util.getMessageSyncError() + ' while searching for drug');
                callback();
            },
            scope: this
        });
    },

    // Helper to assist in REST call, which creates new drugs in OpenMRS db
    _postNewDrug: function(newDrugParam, callback) {
        var newDrugInfo = {
            name: newDrugParam.manufacturer,
            description: newDrugParam.supplier,
            cost: newDrugParam.cost,
            price: newDrugParam.price
        };
        var newDrug = {
            concept: newDrugParam.conceptUuid,
            name: newDrugParam.drugName,
            dosageForm: newDrugParam.dosageForm,
            minimumDailyDose: newDrugParam.minimumDailyDose,
            maximumDailyDose: newDrugParam.maximumDailyDose,
            strength: newDrugParam.strength,
            units: newDrugParam.units,
            drugInfo: newDrugInfo,
            genericName: newDrugParam.genericName
        };
        var newDrugParam = Ext.encode(newDrug);
        Ext.Ajax.request({
            url: HOST + '/ws/rest/v1/raxacore/drug',
            method: 'POST',
            params: newDrugParam,
            disableCaching: false,
            headers: Util.getBasicAuthHeaders(),
            success: function (response) {
                var jsonResponse = Ext.decode(response.responseText);
                Ext.Msg.alert('Success','Drug created successfully');
                newDrug.dosageForm = jsonResponse.dosageForm;
                newDrug.uuid = jsonResponse.uuid;
                callback(newDrug);
            },
            failure: function (response) {
                Ext.Msg.alert('Error','Unable to write to server. Enter all fields.');
                callback();
            },
            scope: this
        });
    },

    /**
     * Creates a new concept in OpenMrs, in case drug is not part of RxNorm/OpenMrs
     */
    postConceptForNewDrug: function(newDrugParam, callback){
        var newConcept = {
            names: [{
                name: newDrugParam.genericName, 
                locale: "en", 
                conceptNameType: "FULLY_SPECIFIED"
            }],
            datatype: localStorage.drugConceptDataTypeUuid,
            conceptClass: localStorage.drugConceptClassUuid
        };
        var newConceptParam = Ext.encode(newConcept);
        Ext.Ajax.request({
            url: HOST + '/ws/rest/v1/concept',
            method: 'POST',
            params: newConceptParam,
            disableCaching: false,
            headers: Util.getBasicAuthHeaders(),
            success: function (response) {
                var jsonResponse = Ext.decode(response.responseText);
                newDrugParam.conceptUuid = jsonResponse.uuid;
                this._postNewDrug(newDrugParam, callback);
            },
            failure: function() {
                Ext.Msg.alert("Error", Util.getMessageSyncError() + ' while adding new drug to database');
                callback();
            },
            scope: this
        });
    },
    
    calculateMedicationQuantity: function(prescription){
        var duration = 1;
        if(prescription.duration!== null){
            duration = prescription.duration;
        }
        var frequency = prescription.frequency;
        console.log(prescription);
        switch(frequency) {
            case 'q.h.' :
                return duration * 24;
            case 'qqh' :
                return duration * 6;
            case 'q.d.s.' :
                return duration * 4;
            case 't.d.s.' :
                return duration * 3;
            case 'b.d' :
                return duration * 2;
            case 'q.d., q1d' || 'q.a.m.' || 'q.p.m.' || 'q4PM' || 'q.h.s.':
                return duration;
            case 'q.a.d.':
                return Math.ceil(duration/2);
            case 't.i.w.':
                return Math.round(duration*3/7);
            case 'QWK' :
                return Math.ceil(duration/7);
            case 'p.r.n':
                return DEFAULT_PRESCRIPTION_QUANTITY;
            case 'q.s.':
                return DEFAULT_PRESCRIPTION_QUANTITY;
            case 'ad lib':
                return DEFAULT_PRESCRIPTION_QUANTITY;
            default :
                return DEFAULT_PRESCRIPTION_QUANTITY;
        }
    },
    
    getDirectionsFromPharmacyAbbreviation: function(abbrev){
        switch(abbrev) {
            case 'q.h.' :
                return "every hour";
            case 'qqh' :
                return "every 4 hours";
            case 'q.d.s.' :
                return "4 times per day";
            case 't.d.s.' :
                return "3 times per day";
            case 'b.d' :
                return "2 times per day";
            case 'q.d., q1d' :
                return "every day";
            case 'q.a.m.' :
                return "every day before noon";
            case 'q.p.m.':
                return "every day after noon";
            case 'q4PM':
                return "every day at 4 PM";
            case 'q.h.s.':
                return "every night at bedtime";
            case 'q.a.d.':
                return "every other day";
            case 't.i.w.':
                return "3x per week";
            case 'QWK' :
                return "once per week";
            case 'p.r.n':
                return "as needed";
            case 'q.s.':
                return "sufficient quantity";
            case 'ad lib':
                return "as needed";
            default :
                return "N/A";
        }
    },

    getInstructionsFromPharmacyAbbrrevation: function(abbrev) {
        switch(abbrev) {
            case 'p.c.' :
                return 'after meals';
            case 'ex aq' :
                return 'with water';
            case 'cc':
                return 'with food';
            case 'cf':
                return 'with food';
            default :
                return "";
        }
    }, 

    //adds the server time difference to account for time zones differences with server
    getTimeAsServerTime: function(time) {
        var newTime = new Date();
        newTime.setTime(time.getTime() + parseInt(localStorage.serverTimeDiff));
        return newTime;
    },

    isMobileSafari: function() {
        return navigator.userAgent.match(/(iPod|iPhone|iPad)/) && navigator.userAgent.match(/AppleWebKit/)
    },
    
    isAndroid: function() {
        return navigator.userAgent.match(/Android/i);
    },

    /**
     * Checks local storage and returns whether current provider has filled in all attributes needed for printing
     */
    hasAllAttributesForPrint: function() {
        for(var i=0; i<Util.REQUIRED_PROVIDER_ATTRIBUTES.length; i++){
            var attributeName = "provider" + Util.REQUIRED_PROVIDER_ATTRIBUTES[i].replace(/\s+/g, '');
            if(!localStorage.getItem(attributeName) || localStorage.getItem(attributeName)===""){
                return false;
            }
        }
        return true;
    },

    //gets Corresponding intake unit for every route of administration for a drug
    getIntakeFormUnit: function(routeOfAdministration){
        switch (routeOfAdministration) {

            case 'Caplet':
                return {
                    singular: 'Caplet',
                    plural: 'Caplets',
                    datatype: 'integer'
                };
                break;

            case 'Capsule XR':
            case 'Capsule':
            case 'CAPS':
            case 'Softgel Capsule':
            case 'Soflet Gel capsule':
            case 'Capsule Retard':
            case 'CAPSULE LB':
            case 'SOFTGEL CAP':
            case 'Respirator Capsule':
            case 'Capsule XL':
            case 'Capsule Extended Release':
            case 'Respiratory Capsule Forte':
                return {
                    singular: 'Capsule',
                    plural: 'Capsules',
                    datatype: 'integer'
                };
                break;

            case 'Drops':
            case 'Nasal Drops':
            case 'Eye Drops':
            case 'Oral Drops':
            case 'Eye/Ear Drps':
            case 'Ear Drops':
                return {
                    singular: 'Drop',
                    plural: 'Drops',
                    datatype: 'integer'
                };
                break;

            case 'Pellets':
                return {
                    singular: 'Pellet',
                    plural: 'Pellets',
                    datatype: 'integer'
                };
                break;

            case 'Accuhaler':
                return {
                    singular: 'Puff',
                    plural: 'Puffs',
                    datatype: 'integer'
                };
                break;

            case 'Dental Rinse':
                return {
                    singular: 'Rinse',
                    plural: 'Rinses',
                    datatype: 'integer'
                };
                break;

            case 'ORAL SUSP':
                return {
                    singular: 'Tablespoon',
                    plural: 'Tablespoons',
                    datatype: 'integer'
                };
                break;

            case 'Tablet':
            case 'TAB':
            case 'Tablet Chewable':
            case 'Tablet Dispersible':
            case 'DT-TAB':
            case 'DT TAB':
            case 'Kid Tablet':
            case 'KID TAB':
            case 'Tablet Sustained Release':
            case 'CHEW TAB':
            case 'Tablet (Mouth Dissolving)':
            case 'MD Tab':
            case 'FORTE TAB':
            case 'Kid Tablet Dispersible':
            case 'Tablet Extended Release':
            case 'Tablet Soluble':
            case 'DS TAB':
            case 'Tablet Long Acting':
            case 'TAB-P':
            case 'Tablet Modified Release':
            case 'Tablet OD':
            case 'Tablet MD':
            case 'Tablet Effervescent':
            case 'TABLET-OD':
            case 'Tablet BD':
            case 'Semi Tablet':
            case 'Tablet SS':
            case 'Tablet Bilayered':
            case 'Tablet LS':
            case 'Tablet PR':
            case 'Tablet/ Chew Tab':
            case 'Tablet EN':
            case 'Tablet XR':
            case 'SR  TAB':
            case 'Tablet SA':
            case 'Tablet DUO':
            case 'Tablet Junior':
            case 'Paediatric Tablet':
            case 'TAB SR':
            case 'TAB KID':
            case 'Tablet Enteric Coated':
            case 'DIS TAB':
            case 'Tablet  Film Coated':
            case 'Tablet Film Coated':
            case 'SR TAB':
            case 'Tablet Controlled Delivery':
            case 'Tablet (MD)':
            case 'Tablet Retard':
            case 'Tablet Gel':
            case 'Tablet P':
            case 'Tablet Film':
            case 'Tablet XL':
            case 'Tablet Instant Release':
            case 'Tablet Sub-lingual':
            case 'Tablet Instause':
            case 'Tender Tablet':
                return {
                    singular: 'Tablet',
                    plural: 'Tablets',
                    datatype: 'float'
                };
                break;
            case 'Syrup':
            case 'DRY SYRUP':
            case 'Vial':
            case 'Liquid':
            case 'DRY SYRYP':
            case 'Oral Solution':
            case 'SYP':
            case 'Vial Liquid':
            case 'Paediatric Liquid':
            case 'Paediatric Syrup':
            case 'Vial (Paed dose)':
            case 'Vial (Multidose)':
                return {
                    singular: 'ml',
                    plural: 'ml',
                    datatype: 'integer'
                };
                break;
            case 'Ampoule':
            case 'Suscap':
            case 'INJ':
            case 'Kit':
            case 'Combipack':
            case 'Infusion':
            case 'Cream':
            case 'CAP':
            case 'AMP':
            case 'Suspension':
            case 'SUSP':
            case 'Injection':
            case 'Powder':
            case 'Tooth Paste':
            case 'DT':
            case 'Hospital Concentrate Liquid':
            case 'Tablet Controlled Release':
            case 'Ointment':
            case 'Gel':
            case 'Lotion':
            case 'Capsule Sustained Release':
            case 'I.V. Fluid':
            case 'Cake':
            case 'Face Pack':
            case 'Face Wash Gel':
            case 'Vial + Ampoule':
            case 'DRY SUSP':
            case 'Cartridge':
            case 'Sachet':
            case 'Inhaler':
            case 'Spacer':
            case 'Granules':
            case 'Solution':
            case 'Sustained Release':
            case 'Lozenges':
            case 'Tube':
            case 'Injection Vial':
            case 'Vial Injection':
            case 'Vial Paediatric':
            case 'Vial Double Strength':
            case 'Vial Neonatal':
            case 'Drops Neonatal':
            case 'Suppositories':
            case 'Tablet Kit':
            case 'Tablet Duplex':
            case 'Nasal Spray':
            case 'Spray':
            case 'Respule':
            case 'Rotacaps':
            case 'Eye Ointment':
            case 'Injection in Prefilled Syringe':
            case 'Dragee Retard':
            case 'KID':
            case 'Aerosol':
            case 'Metered Dose':
            case 'DROP':
            case 'Elixir':
            case 'Capsule Timed Release':
            case 'Vaginal Pessaries':
            case 'Foam':
            case 'Vial Multidose':
            case 'Softule':
            case 'Vial & Solvent':
            case 'Misthaler':
            case 'Transcaps':
            case 'Dry Powder Inhaler':
            case 'Nasal Spray Solution':
            case 'Mouth Paint':
            case 'Vaginal Tablet':
            case 'Vaginal Cream':
            case 'Vaginal Suppositories':
            case 'Softgel Suppositories':
            case 'Softgel Pessaries':
            case 'Dialysis Fluid':
            case 'Tablet + Solvent':
            case 'Combipack Part I & II':
            case 'Rediuse':
            case 'Paediatric Drops':
            case 'Intravenous Fat Emulsion':
            case 'D.S.':
            case 'Capsule Controlled Release':
            case 'Disposable syringe':
            case 'Oil':
            case 'Applicaps':
            case 'KAPSEAL':
            case 'Bottle':
            case 'Injection Intra Venous':
            case 'Soap Cake':
            case 'Shampoo':
            case 'Vial injection (Neonatal)':
            case 'DS':
            case 'Paediatric Suspension':
            case 'Canister':
            case 'Effervescent Granules':
            case 'Solvent for Injection':
            case 'Respirator Solution':
            case 'Aqueous Gel':
            case 'Ointment with applicator':
            case 'Vialflex iv bag':
            case 'FORTE':
            case 'Vial (Lypholised)':
            case 'AMPULE':
            case 'Multihaler':
            case 'Injection Intra Muscular':
            case 'Transdermal Patch':
            case 'Spanule':
            case 'Inhalent':
            case 'Strip (standard)':
            case 'Gum Gel':
            case 'Neohaler':
            case 'Injection in Graduated Syringe':
            case 'Biscuit':
            case 'Pearls':
            case 'Injection IV Concentrated':
            case 'Jelly':
            case 'Surgical irrigation solution':
            case 'Ovules':
            case 'Vial + Ampoule diluent':
            case 'Insulin Device':
            case 'Caplet Controlled Release':
            case 'Optiset':
            case 'Wafer':
            case 'Pouch':
            case 'Oral Paste':
            case 'Paste':
            case 'Douche':
            case 'Caplet Extended Release':
            case 'Rapitab':
            case 'Paediatric Vial':
            case 'Paint':
            case 'Vial (HMG)':
            case 'Opticop':
            case 'Pessaries':
            case 'Intrauterine system':
            case 'Insulin Injection':
            case 'Capsule Controlled Delivery':
            case 'Copper':
            case 'Dragee Forte':
            case 'Oral Suspension':
            case 'Vial Intra Venous':
            case 'Transdermal Therapeutic System-5':
            case 'Transdermal Therapeutic System-10':
            case 'Needle':
            case 'Device':
            case 'Intra Venous injection':
            case 'Eye/Ear Drops':
            case 'Dispersible Suspension':
            case 'Vial + Drops':
            case 'Combikit':
            case 'Vaginal Applicator':
            case 'Softabs':
            case 'Soflet Gelcapsule':
            case 'Capsule Pack':
            case 'Dragee':
            case 'Vaccine':
            case 'Nutridisc pack':
            case 'Perfusion solution':
            case 'Mouthwash':
            case 'Tablet Dispersible Forte':
            case 'Transpule':
            case 'Oral Rinse Solution':
            case 'MCT Oil':
            case 'Gum Paint':
            case 'Capsule LA Extended Release':
            case 'Vial (10 dose)':
            case 'Diskette':
            case 'Vial + Vial':
            case 'Inhalent MDI':
            case 'Instause':
            case 'Dragee Sustained Release':
            case 'Applicators':
            case 'Opticap':
            case 'Vial + Ser. (PS)':
            case 'Pump spray':
            case 'Rectal tubes':
            case 'Vaginal Ovules':
            case 'Vaginal Gel':
            case 'Effervescent Tablet':
            case 'Effervescent Drink Crystals':
            case 'Patches':
            case 'Neb sol':
            case 'Enema':
            case 'Emulsion':
            case 'Nail Paint':
            case 'Vaginal Douche':
            case 'Dry Powder Spray':
            case 'Topical Solution':
            case 'Buccal Spray':
            case 'Tincture':
            case 'Teething Gel':
            case 'Mouth Spray':
            case 'Mask (Child)':
            case 'Nasal Douche':
            case 'Cleanser':
            case 'Foot Cream':
            case 'Hand Cream':
            case 'Irrigation Solution':
            case 'Pen':
            case 'Crystals':
            case 'Oral Liquid':
            case 'Gum':
            case 'Soap':
            case 'Eye Lotion':
            case 'Nasal Gel':
            case 'Evohaler':
            case 'Oral Vaccine':
            case 'Stat dose':
            case 'Expectorant':
            case 'Bag':
            case 'Mask(adult)':
            case 'Mask(infant)':
            case 'Turbohaler':
            case 'Heel balm':
            case undefined:
            case '-':
            case '':
                return {
                    singular: 'unit',
                    plural: 'units',
                    datatype: 'float'
                };
                break;

            case 'Mouth Wash':
                return {
                    singular: 'Wash',
                    plural: 'Washes',
                    datatype: 'integer'
                };
                break;
        }
    },

    isInCareHospital: function() {
        return localStorage.locationName === "Sir Gangaram Hospital";
    },


   /**
     * Function used to fix a bug where large images get squashed in iOS 6 & 7
     * Credit: https://github.com/stomita/ios-imagefile-megapixel
     * Returns the ratio which the vertical image is squished by (1 if not squished)
     */
    detectVerticalSquash: function(img) {
        var iw = img.naturalWidth, ih = img.naturalHeight;
        var canvas = document.createElement('canvas');
        canvas.width = 1;
        canvas.height = ih;
        var ctx = canvas.getContext('2d');
        ctx.drawImage(img, 0, 0);
        var data = ctx.getImageData(0, 0, 1, ih).data;
        var sy = 0;
        var ey = ih;
        var py = ih;
        while (py > sy) {
            var alpha = data[(py - 1) * 4 + 3];
            if (alpha === 0) {
                ey = py;
            } else {
                sy = py;
            }
            py = (ey + sy) >> 1;
        }
        var ratio = (py / ih);
        return (ratio===0)?1:ratio;
    },

    /**
     * Rotate the thumbnail based on
     */
    orientImage: function(image, orientation) {
        var orientation = parseInt(orientation);
        alert(orientation);
        if(orientation === 2){
            image.scale.x =-1;
        }else if(orientation === 3){
            image.rotateDeg(180);
            image.setX(image.getX()+image.getWidth());
            image.setY(image.getY()+image.getHeight());
        }else if(orientation === 4){
            image.scale.x =-1;
            image.rotateDeg(180);
        }else if(orientation === 5){
            image.rotateDeg(90);
            image.scale.x =-1;
            image.setX(image.getX()+image.getWidth());
        }else if(orientation === 6){
            image.rotateDeg(90);
            image.setX(image.getX()+image.getWidth());
        }else if(orientation === 7){
            image.scale.y = -1;
            image.rotateDeg(360);
            image.setX(image.getX()+image.getWidth());
        }else if(orientation === 8){
            image.rotateDeg(360);
            image.setX(image.getX()+image.getWidth());
        }
        return image;
    },

    /**
     * Orient and draw image on canvas (for profile photo)
     * params: image, orientation, canvas, ctx
     */

    orientAndDrawImage: function(config) {
        var orientation = parseInt(config.orientation);
        if(orientation === 2){
            config.ctx.translate(config.canvas.width, 0);
            config.ctx.scale(-1, 1);
            config.ctx.drawImage(config.image, 0, 0, config.canvas.width, config.canvas.height);
        } else if(orientation === 3){
            config.ctx.rotate(Math.PI);
            config.ctx.drawImage(config.image, 0, -config.canvas.width, config.canvas.width, config.canvas.height);
        } else if(orientation === 4){
            config.ctx.rotate(Math.PI);
            config.ctx.drawImage(config.image, 0, 0, config.canvas.width, config.canvas.height);
        } else if(orientation === 5){
            config.ctx.rotate(Math.PI/2);
            config.ctx.translate(config.canvas.width, 0);
            config.ctx.scale(-1, 1);
            config.ctx.drawImage(config.image, 0, -config.canvas.width, config.canvas.width, config.canvas.height);
        } else if(orientation === 6){
            config.ctx.rotate(Math.PI/2);
            config.ctx.drawImage(config.image, 0, -config.canvas.width, config.canvas.width, config.canvas.height);
        } else if(orientation === 7){
            config.ctx.rotate(-Math.PI/2);
            config.ctx.translate(config.canvas.width, 0);
            config.ctx.scale(-1, 1);
            config.ctx.drawImage(config.image, 0, -config.canvas.width, config.canvas.width, config.canvas.height);
        } else if(orientation === 8){
            config.ctx.rotate(-Math.PI/2);
            config.ctx.drawImage(config.image, 0, -config.canvas.width, config.canvas.width, config.canvas.height);
        } else {
            config.ctx.drawImage(config.image, 0, 0, config.canvas.width, config.canvas.height);
        }
    }

}
